### ISSUE TITLE
Windows executable

### ISSUE THREAD

**Issue by matthew-d-jones** [ess-dmsc/nexus-geometry-constructor#27]
Having a single file executable or installer early in development would make life easier for potential testers of the application.
`pyinstaller` and `pyupdater` are probably the standard tools for this at the moment, worth checking though.

**Comment by ACLay** [comment]
PyInstaller has a [known bug](https://github.com/pyinstaller/pyinstaller/issues/3689) that's preventing it building our demo QML app, so I'm looking into alternatives at the moment.

**Comment by matthew-d-jones** [comment]
If there is no obvious alternative then waiting for the PR to be merged to fix that bug is also an option.

**Comment by ACLay** [comment]
There are [a few other options](https://docs.python-guide.org/shipping/freezing/) to at least try out.

**Comment by ACLay** [comment]
Adding that branch `git+https://github.com/tobinjones/pyinstaller.git` to requirements does seem to fix the initial bug. It does however reveal another pysinstaller-pyside2-QML specific bug, which I think is the one that was guessed to exist [here](https://github.com/pyinstaller/pyinstaller/issues/3711#issuecomment-418678385) based on a similar bug for pyinstaller-PyQt5-QML.

However, [cx_freeze](https://pypi.org/project/cx_Freeze/) is looking very promising, already have a slightly modified version of the program running in it.
